version: '3'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    image: airzone-test-app:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/airzone-test

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
