version: '3'
services:
  airzone-test-app:
    container_name: airzone-test-app
    restart: always
    build: .
    image: airzone-test-app:latest
    ports:
      - "4000:3000"
    links:
      - mongo
    environment:
      - NODE_ENV=docker
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: aizone-test-mongodb
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    logging:
      driver: "none"

volumes:
  mongodb_data:
